runtime: python311

# Basic scaling configuration
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

# Environment variables
env_variables:
  FLASK_ENV: "production"
  # Add your Supabase and other environment variables here
  GOOGLE_API_KEY: "AIzaSyCady9UPrkTa63OXIC6REhkX_tya9eeR58"
  SUPABASE_URL: "https://syumnssymzdnzgcvxwgm.supabase.co"
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dW1uc3N5bXpkbnpnY3Z4d2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTQ4MDQsImV4cCI6MjA2NTI3MDgwNH0.bZJqI0p2we6nqPzsO_xnDM43peeoS7QDCl_wtOL6ZXA"

# Handlers for URL routing
handlers:
# Serve static files
- url: /static
  static_dir: static
  secure: always

# Route all other requests to the Flask app
- url: /.*
  script: auto
  secure: always

# Optional: Set session affinity for WebSocket support
network:
  session_affinity: true